application:
  protocol: http
  host: "[::]"
  base_url: "[::]"

debug: false

redis:
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60

mongo: 
  database: 'test'