application:
  protocol: https
  host: 0.0.0.0
  base_url: ""

debug: false

redis:
  uri: "<your_redis_uri>"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60