# fly.toml app configuration file generated for dev-playbot-backend on 2023-12-24T13:32:49-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dev-playbot-backend"
primary_region = "ord"

[build]

[deploy]
  strategy = "bluegreen"

[http_service]
  internal_port = 5000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health-check/"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
