name: Fly Deploy
on:
  push:
    branches:
      - main
      - 'dev-*'
    paths:
      - 'discord-bot/**'
  workflow_dispatch:
  workflow_run:
    workflows: [ESLint]
    types:
      - completed
jobs:
  deploy_prod:
    if: github.ref == 'refs/heads/main' &&  ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy discord-bot to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy --remote-only -c ./prod.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_PROD_DISCORD_BOT }}
        working-directory: discord-bot
  deploy_dev:
    if: startsWith(github.ref, 'refs/heads/dev-') &&  ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy discord-bot to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy --remote-only  -c ./dev.fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DEV_DISCORD_BOT }}
        working-directory: discord-bot