name: Pulumi
on:
  - pull_request
permissions:
      id-token: write
      contents: read
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '20'

      - run: npm install
        working-directory: infra
        name: 📝 Running npm install

      - uses: pulumi/actions@v3
        name: 👀 Checking infra changes
        with:
          command: preview
          stack-name: dnhess/infra/dev # When using an individual account, only use stack-name.  
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
