name: Pulumi
on:
  push:
    branches:
      - main
permissions:
      id-token: write
      contents: read
jobs:
  preview:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: 💼 Checking out code
      - uses: actions/setup-node@v3.5.0
        name: ☊ Setup Node
        with:
          node-version: '20'

      - run: npm install
        working-directory: infra
        name: 📝 Running npm install

      - name: 📓 Creating .env file
        run: |
          echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> ./discord-bot/.env
          echo "AMPLITUDE_API_KEY=${{ secrets.AMPLITUDE_API_KEY }}" >> ./discord-bot/.env
          echo "CLIENT_ID=${{ secrets.PROD_CLIENT_ID }}" >> ./discord-bot/.env
          echo "DISCORD_TOKEN=${{ secrets.PROD_DISCORD_TOKEN }}" >> ./discord-bot/.env
          echo "MONODB_URL=${{ secrets.PROD_MONODB_URL }}" >> ./discord-bot/.env
          echo "ROLLBAR_ACCESS_TOKEN=${{ secrets.PROD_ROLLBAR_ACCESS_TOKEN }}" >> ./discord-bot/.env

      - uses: pulumi/actions@v3
        name: 🏗️ Deploying infra
        with:
          command: up
          stack-name: dnhess/infra/prod  
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
