name: Pulumi
on:
  - pull_request
permissions:
      id-token: write
      contents: read
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '20'

      - run: npm install
        working-directory: infra

      - name: Create .env file
        run: |
          echo "BASE_API_URL=${{ secrets.BASE_API_URL }}" >> ./discord-bot/.env
          echo "AMPLITUDE_API_KEY=${{ secrets.AMPLITUDE_API_KEY }}" >> ./discord-bot/.env
          echo "CLIENT_ID=${{ secrets.DEV_CLIENT_ID }}" >> ./discord-bot/.env
          echo "DISCORD_TOKEN=${{ secrets.DEV_DISCORD_TOKEN }}" >> ./discord-bot/.env
          echo "GUILD_ID=${{ secrets.DEV_GUILD_ID }}" >> ./discord-bot/.env
          echo "MONODB_URL=${{ secrets.DEV_MONODB_URL }}" >> ./discord-bot/.env
          echo "ROLLBAR_ACCESS_TOKEN=${{ secrets.DEV_ROLLBAR_ACCESS_TOKEN }}" >> ./discord-bot/.env

      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dnhess/infra/dev # When using an individual account, only use stack-name.  
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
