name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '20'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DISCORDBOT_AZURE_CREDENTIALS }}
      - run: npm install
        working-directory: infra
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dnhess/infra/dev # When using an individual account, only use stack-name.  
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}