name: Pulumi
on:
  - pull_request
permissions:
      id-token: write
      contents: read
jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.0
        with:
          node-version: '20'
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - run: npm install
        working-directory: infra
      - uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dnhess/infra/dev # When using an individual account, only use stack-name.  
          work-dir: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}